#!/bin/sh
set -e

MEMHOOK_DIR="$(readlink -f `dirname $0`/..)"

clean_dir "$MEMHOOK_BUILD_ROOT" && pushd "$MEMHOOK_BUILD_ROOT"

if [ ! "$TOOLCHAIN_HOST" = "" ]; then
    cat <<EOF >./toolchain.cmake
SET(TOOLCHAIN_HOST $TOOLCHAIN_HOST)
SET(TOOLCHAIN_ROOT $TOOLCHAIN_ROOT)
SET(CMAKE_SYSTEM_PROCESSOR $TOOLCHAIN_ARCH)
SET(CMAKE_SYSTEM_NAME    Linux)
SET(CMAKE_SYSTEM_VERSION 2.6.18)
SET(CMAKE_C_COMPILER   ${TOOLCHAIN_HOST}-gcc)
SET(CMAKE_CXX_COMPILER ${TOOLCHAIN_HOST}-c++)
SET(CMAKE_FIND_ROOT_PATH $TOOLCHAIN_ROOT $BUILD_ROOT)
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
EOF
    MEMHOOK_CMAKE_ARGS=-DCMAKE_TOOLCHAIN_FILE=./toolchain.cmake
fi

cmake -GNinja $MEMHOOK_DIR $MEMHOOK_CMAKE_ARGS \
    -DBOOST_ROOT="$BOOST_PRIVATE_BUILD_ROOT" \
    -DLIBUNWIND_ROOT="$LIBUNWIND_BUILD_ROOT" \
    -DCMAKE_BUILD_TYPE=Release \
    -DMEMHOOK_USE_BOOST_PRIVATE=1 && ninja

popd # MEMHOOK_BUILD_ROOT
